BirdLogger.Web.MVC/Controllers/LoggerController.cs
using BirdLogger.Models;
using BirdLogger.service;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BirdLogger.Web.MVC.Controllers
{
    [Authorize]
    public class LoggerController : Controller
    {
        // GET: Logger
        public ActionResult Index()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new LoggerService(userId);
            var model = service.GetLogger();
            
            return View(model);
        }

        public ActionResult Create()
        {
            return View();
            
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(LoggerCreate model)
        {
            if (!ModelState.IsValid) return View(model);
            

            var service = CreateLoggerService();

            if (service.CreateLogger(model))
            {
              TempData["SaveResult"] = "The Bird was created.";
              return RedirectToAction("Index");
            };

            ModelState.AddModelError("", "The Bird could not be created.");

            return View(model);
        }

        public ActionResult Details(int id)
        {
            var svc = CreateLoggerService();
            var model = svc.GetLoggerById(id);

            return View(model);
        }

        public ActionResult Edit(int id)
        {
            var service = CreateLoggerService();
            var detail = service.GetLoggerById(id);
            var model = new LoggerEdit
            {
                LoggerId = detail.LoggerId,
                OwnerId = detail.OwnerId,
                Type = detail.Type,
                Location = detail.Location,
                Size = detail.Size,
                Color = detail.Color,
                Activity = detail.Activity,
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, LoggerEdit model)
        {  
            if (!ModelState.IsValid) return View(model);

            if (model.LoggerId !=id)
            {
                ModelState.AddModelError("", "Id Mismatch");
                return View(model);
            }

            var service = CreateLoggerService();

            if (service.UpdateLogger(model))
            {
                TempData["SaveResult"] = "Your Bird was updated.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Your Bird could not be updated.");
            return View(model);
        }

        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var svc = CreateLoggerService();
            var model = svc.GetLoggerById(id);

            return View(model);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePost(int id)
        {
            var service = CreateLoggerService();
            service.DeleteLogger(id);
            TempData["SaveResult"] = "Your Bird was deleted.";
            return RedirectToAction("Index");
        }

        private LoggerService CreateLoggerService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new LoggerService(userId);
            return service;
        }
    }
}

BirdLogger.Web.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="https://fonts.googleapis.com/css?family=Poiret+One|Special+Elite&display=swap" rel="stylesheet">

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Bird", "Index", "Logger")</li>
                    }
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Nest", "Index", "Nest")</li>
                    }

                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Journal", "Index", "Journal")</li>
                    }

                    <!--@*<li>Html.ActionLink("About", "About", "Home")*@</li>-->
                    <li>@*Html.ActionLink("Contact", "Contact", "Home")*@</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
   </div>
  
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - The Bird Logger Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>